//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFHistoryTeachings
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StorePath { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long TeacherId { get; set; }
    }
}
