//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFTeachers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PenSerial { get; set; }
        public string PenNo { get; set; }
        public Nullable<int> PenUID { get; set; }
        public Nullable<int> PenNum { get; set; }
        public Nullable<int> VoteNum { get; set; }
        public long UserId { get; set; }
        public bool Approved { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public long OwnerId { get; set; }
    
        public virtual SFSchools SFSchools { get; set; }
    }
}
