//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFWords
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Xueqing { get; set; }
        public string Expert { get; set; }
        public string Legend { get; set; }
        public string Structure { get; set; }
        public int Strokes { get; set; }
        public string Part { get; set; }
        public Nullable<int> Exstrokes { get; set; }
        public string Make { get; set; }
    }
}
